Layout page
js-tasks-ru/htmlcss-20230411_l-milaropot pull request #3
Opened 2023-04-17 19:15 UTC by Ropot171

2023-04-17 19:16 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-17 19:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-18 09:03 UTC, GSemikozov requested changes

2023-04-18 09:03 UTC, GSemikozov commented on components/footer/footer.css
> +    position: absolute;
позиционирование, жестко фиксированную ширину и высоту не стоит указывать без явной необходимости - удалим эту часть из всех элементов и блоков)

2023-04-18 11:40 UTC, Ropot171 commented on components/footer/footer.css
> +    position: absolute;
исправила)

2023-04-18 11:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-18 17:02 UTC, GSemikozov approved these changes

2023-04-18 17:02 UTC, merged