Skeleton
js-tasks-ru/htmlcss-20230411_l-milaropot pull request #7
Opened 2023-05-01 12:46 UTC by Ropot171

2023-05-01 12:47 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-01 14:56 UTC, GSemikozov requested changes

2023-05-01 14:56 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line__1 {
.skeleton__line_short

2023-05-01 14:56 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line__2 {
.skeleton__line_middle

2023-05-03 13:40 UTC, GSemikozov requested changes

2023-05-03 13:40 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +          <div class = "sleleton_header">
skeleton__header

2023-05-03 14:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-03 14:45 UTC, GSemikozov approved these changes

2023-05-03 14:45 UTC, merged